src/objects/OAuth_Token__c.object
<CustomObject>
    <fields>
        <fullName>OAuth_Service__c</fullName>
        <label>OAuth Service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>OAuth Tokens</relationshipLabel>
        <relationshipName>OAuth_Tokens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OAuth_Token_Secret__c</fullName>
        <label>OAuth Token Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Token__c</fullName>
        <label>OAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OAuth_Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAccess</label>
        <type>Checkbox</type>
    </fields>
    <label>OAuth Token</label>
    <nameField>
        <displayFormat>OT-{00000000}</displayFormat>
        <label>OAuth Token No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token_URL__c</fullName>
        <label>Access Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Authorization_Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Request Header (Authorization: Bearer)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request Header (Authorization: OAuth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URI Query Parameter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Request_Token_URL__c</fullName>
        <label>Request Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Services</pluralLabel>
    <recordTypes>
        <fullName>OAuth1</fullName>
        <active>true</active>
        <description>OAuth 1.0 Service</description>
        <label>OAuth1</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OAuthTwitterSampleControllerTest.cls
@isTest
private class OAuthTwitterSampleControllerTest {
    public static OAuthService__c createTestService() {
        OAuthService__c s = new OAuthService__c(
            Name = 'Twitter',
            Consumer_Key__c = 'consumerkey',
            Consumer_Secret__c = 'consumersecret',
            Request_Token_URL__c = 'https://api.twitter.com/oauth/request_token',
            Authorization_URL__c = 'https://api.twitter.com/oauth/authorize',
            Access_Token_URL__c = 'https://api.twitter.com/oauth/access_token',
            Redirect_URL__c = 'https://localhost/oauth1/done',
            OwnerId = UserInfo.getUserId(),
            RecordTypeId = OAuthUtil.getOAuthServiceRecordTypeId('OAuth1'),
            Scope__c = 'full',
            Authorization_Type__c = 'Request Header (Authorization: Bearer)'
        );
        insert s;
        return s;
    }

    public static OAuth_Token__c createTestToken(OAuthService__c  s, Boolean isAccess) {
        OAuth_Token__c t = new OAuth_Token__c(
            OAuth_Service__c = s.Id,
            OAuth_Token__c = 'token',
            OAuth_Token_Secret__c = 'secret',
            Owner__c = s.OwnerId,
            isAccess__c = isAccess
        );
        insert t;
        return t;
    }

    public static testMethod void testInit() {
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService();
        OAuthTwitterSampleController t = new OAuthTwitterSampleController();

        Test.startTest();
        t.init();
        Test.stopTest();
    }

    public static testMethod void testInitComplete() {
        PageReference completePage = new PageReference('/oauth1/done?oauth_token=token');
        completePage.getHeaders().put('Host', 'localhost');
        Test.setCurrentPage(completePage);
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService();
        createTestToken(s1, false);
        OAuthTwitterSampleController t = new OAuthTwitterSampleController();

        Test.startTest();
        t.init();
        Test.stopTest();
    }

    public static testMethod void testInitToken() {
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService();
        createTestToken(s1, true);
        OAuthTwitterSampleController t = new OAuthTwitterSampleController();

        Test.startTest();
        t.init();
        Test.stopTest();
    }

    public static testMethod void testTwitter() {
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        System.currentPageReference().getParameters().put('@test', 'test');
        OAuthService__c s1 = createTestService();
        createTestToken(s1, true);
        OAuthTwitterSampleController t = new OAuthTwitterSampleController();

        Test.startTest();
        t.getFeed();
        t.status = 'test';
        t.post();
        Test.stopTest();
    }
}