src/objects/OAuth2_Token__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expires_In__c</fullName>
        <label>Expires In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OAuth_Service__c</fullName>
        <label>OAuth Service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>OAuth2 Tokens</relationshipLabel>
        <relationshipName>OAuth2_Tokens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OAuth2_Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth2 Token</label>
    <nameField>
        <displayFormat>OT2-{00000000}</displayFormat>
        <label>OAuth2 Token No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OAuth2 Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token_URL__c</fullName>
        <label>Access Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Response_Type__c</fullName>
        <label>Response Type</label>
        <picklist>
            <picklistValues>
                <fullName>code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Services</pluralLabel>
    <recordTypes>
        <fullName>OAuth2</fullName>
        <active>true</active>
        <description>OAuth 2.0 Service</description>
        <label>OAuth2</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OAuth2.cls
public class OAuth2 extends OAuth {
    private OAuth2_Token__c token;

    public OAuth2() {
    }
    public OAuth2(Id serviceId) {
        this(serviceId, UserInfo.getUserId());
    }
    public OAuth2(Id serviceId, Id userId) {
        try {
            service = [
                Select
                    Name, Response_Type__c, Consumer_Key__c, Consumer_Secret__c,
                    Authorization_URL__c, Access_Token_URL__c, Redirect_URL__c, Scope__c, State__c,
                    (Select Access_Token__c, Refresh_Token__c, Expires_In__c FROM OAuth2_Tokens__r WHERE Owner__c = :userId Order By CreatedDate DESC Limit 1)
                From
                    OAuthService__c
                WHERE
                    Id = :serviceId
            ];
            if (service.OAuth2_Tokens__r.size() > 0) {
                token = service.OAuth2_Tokens__r.get(0);
            }
        } catch (Exception e) {
            throw new OAuth2Exception('no service');
        }
    }

    public override PageReference authorization() {
        PageReference redirect = new PageReference(service.Authorization_URL__c);
        redirect.getParameters().put('response_type', service.Response_Type__c);
        redirect.getParameters().put('client_id', service.Consumer_Key__c);
        if (service.Redirect_URL__c != null) {
            redirect.getParameters().put('redirect_uri', service.Redirect_URL__c);
        }
        if (service.Scope__c != null) {
            redirect.getParameters().put('scope', service.Scope__c);
        }
        if (service.State__c != null) {
            redirect.getParameters().put('state', service.State__c);
        }
        return redirect;
    }

    public override Boolean isCompleteUrl() {
        PageReference current = ApexPages.currentPage();
        if (super.isCompleteUrl() && current.getParameters().containsKey('code')) {
            return true;
        }
        return false;
    }

    public override Boolean complete(Map<String, String> parameters) {
        // error
        if (parameters.containsKey('error')) {
            throw new OAuth2Exception(parameters);
        }
        String code = parameters.get('code');
        return getAccessTokenAuthorizationCode(code);
    }

    private String getAccessTokenCommonBody(String grant_type, String scope) {
        String body =
            'grant_type=' + grant_type +
            '&client_id=' + EncodingUtil.urlEncode(service.Consumer_Key__c, 'UTF-8');
        if (scope != null) {
            body += '&scope=' + EncodingUtil.urlEncode(scope, 'UTF-8');
        }
        return body;
    }
    private String getAccessTokenCommonBody(String grant_type) {
        return getAccessTokenCommonBody(grant_type, null);
    }

    /* grant_type=authorization_code */
    public Boolean getAccessTokenAuthorizationCode(String code) {
        String body =
            getAccessTokenCommonBody('authorization_code', service.Scope__c) + // scope間違い
            '&client_secret=' + EncodingUtil.urlEncode(service.Consumer_Secret__c, 'UTF-8') +
            '&code=' + EncodingUtil.urlEncode(code, 'UTF-8');
        if (service.Redirect_URL__c != null) {
            body += '&redirect_uri=' + EncodingUtil.urlEncode(service.Redirect_URL__c, 'UTF-8');
        }
        token = getAccessToken(body);
        insert token;
        return true;
    }

    /* grant_type=password */
    public Boolean getAccessTokenAuthorizationPassword(String username, String password) {
        String body =
            getAccessTokenCommonBody('password', service.Scope__c) + // scope間違い
            '&client_secret=' + EncodingUtil.urlEncode(service.Consumer_Secret__c, 'UTF-8') +
            '&username=' + EncodingUtil.urlEncode(username, 'UTF-8') +
            '&password=' + EncodingUtil.urlEncode(password, 'UTF-8');
        token = getAccessToken(body);
        insert token;
        return true;
    }

    /* grant_type=assertion */
    public Boolean getAccessTokenAuthorizationAssertion(String assertion_type, String assertion) {
        String body =
            getAccessTokenCommonBody('assertion', service.Scope__c) + // scope間違い
            '&assertion_type=' + EncodingUtil.urlEncode(assertion_type, 'UTF-8') +
            '&assertion=' + EncodingUtil.urlEncode(assertion, 'UTF-8');
        token = getAccessToken(body);
        insert token;
        return true;
    }

    /* grant_type=refresh_token */
    public Boolean getAccessTokenRefreshToken() {
        if (token == null || token.Refresh_Token__c == null) {
            return false;
        }
        String body =
            getAccessTokenCommonBody('refresh_token', service.Scope__c) + // scope間違い
            '&refresh_token=' + EncodingUtil.urlEncode(token.Refresh_Token__c, 'UTF-8');
        OAuth2_Token__c t = getAccessToken(body);
        if (t.Access_Token__c != null) {
            token.Access_Token__c = t.Access_Token__c;
        }
        if (t.Expires_In__c != null) {
            token.Expires_In__c = t.Expires_In__c;
        }
        if (t.Refresh_Token__c != null) {
            token.Refresh_Token__c = t.Refresh_Token__c;
        }
        if (t.Scope__c != null) {
            token.Scope__c = t.Scope__c;
        }
        return true;
    }

    private OAuth2_Token__c getAccessToken(String body) {
        System.debug('getAccessToken body: ' + body);
        HttpRequest req = new HttpRequest();
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        req.setMethod('POST');
        req.setEndpoint(service.Access_Token_URL__c);
        req.setBody(body);
        HttpResponse res = send(req);

        String res_body = getResponseBody(res);
        String res_content_type = getContentType(res);
        System.debug('res_body(' + res_content_type+ ') = ' + res_body);
        if (res_body == null) {
            throw new OAuth2Exception('res_body = null');
        }

        Map<String,String> parameters;
        if (res_content_type != null && res_content_type.startsWith('application/json')) {
            parameters = getJsonParameters(res_body);
        } else {
            parameters = splitParameters(res_body);
        }
        String error = parameters.get('error');
        if (error != null) {
            throw new OAuth2Exception(parameters, res);
        }
        if (!parameters.containsKey('access_token')) {
            throw new OAuth2Exception(null, 'access_toke = null', null, null, null, res);
        }

        String expires_in_str = parameters.get('expires_in');
        Integer expires_in = null;
        if (expires_in_str != null) {
            expires_in = Integer.valueOf(expires_in_str);
        }

        OAuth2_Token__c t = new OAuth2_Token__c(
            Owner__c = UserInfo.getUserId(),
            OAuth_Service__c = service.Id,
            Access_Token__c = parameters.get('access_token'),
            Expires_In__c = expires_in,
            Refresh_Token__c = parameters.get('refresh_token'),
            Scope__c = parameters.get('scope')
        );
        return t;
    }

    public override Boolean hasToken() {
        return this.token != null;
    }

    public override HttpResponse rest(HttpRequest req) {
        if (token != null) {
            req.setHeader('Authorization', 'OAuth ' + token.Access_Token__c);
        }
        HttpResponse res = send(req);
        Integer status_code = res.getStatusCode();
        if (status_code / 100 == 4) {
            OAuth2Exception e = new OAuth2Exception(res); 
            if (/*e.error == 'expired_token' && */getAccessTokenRefreshToken()) {
                req.setHeader('Authorization', 'OAuth ' + token.Access_Token__c);
                res = send(req);
                update token;
                return res;
            }
            throw e;
        }
        return res;
    }
}