src/objects/OAuth_Token__c.object
<CustomObject>
    <fields>
        <fullName>OAuth_Service__c</fullName>
        <label>OAuth Service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>OAuth Tokens</relationshipLabel>
        <relationshipName>OAuth_Tokens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OAuth_Token_Secret__c</fullName>
        <label>OAuth Token Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Token__c</fullName>
        <label>OAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OAuth_Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAccess</label>
        <type>Checkbox</type>
    </fields>
    <label>OAuth Token</label>
    <nameField>
        <displayFormat>OT-{00000000}</displayFormat>
        <label>OAuth Token No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token_URL__c</fullName>
        <label>Access Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Authorization_Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Request Header (Authorization: Bearer)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request Header (Authorization: OAuth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URI Query Parameter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Request_Token_URL__c</fullName>
        <label>Request Token URL</label>
        <type>Url</type>
    </fields>
    <label>OAuth Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Services</pluralLabel>
    <recordTypes>
        <fullName>OAuth1</fullName>
        <active>true</active>
        <description>OAuth 1.0 Service</description>
        <label>OAuth1</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OAuth1Test.cls
@isTest
private class OAuth1Test {
    public static OAuthService__c createTestService(String signature_method) {
        OAuthService__c s = new OAuthService__c(
            Name = 'test1234',
            Consumer_Key__c = 'consumerkey',
            Consumer_Secret__c = 'consumersecret',
            Signature_Method__c = signature_method,
            Access_Token_URL__c = 'https://test/oauth1/token',
            Authorization_URL__c = 'https://test/oauth1/auth',
            Redirect_URL__c = 'https://localhost/oauth1/done',
            OwnerId = UserInfo.getUserId(),
            RecordTypeId = OAuthUtil.getOAuthServiceRecordTypeId('OAuth1'),
            Request_Token_Url__c = 'https://test/oauth/request_token',
            Authorization_Type__c = 'Request Header (Authorization: OAuth)'
        );
        insert s;
        return s;
    }

    public static OAuth_Token__c createTestToken(OAuthService__c  s, Boolean isAccess) {
        OAuth_Token__c t = new OAuth_Token__c(
            OAuth_Service__c = s.Id,
            OAuth_Token__c = 'token',
            OAuth_Token_Secret__c = 'secret',
            Owner__c = s.OwnerId,
            isAccess__c = isAccess
        );
        insert t;
        return t;
    }

    public static testMethod void testNewService() {
        OAuthService__c s = createTestService('HMAC-SHA1');
        OAuth_Token__c t = createTestToken(s, true);
        Test.startTest();
        // success
        s.Redirect_URL__c = '/oauth/request_token';
        update s;
        OAuth1 o1 = new OAuth1(s.Id);
        OAuth1 o2 = OAuth1.newInstanceByToken(t.OAuth_Token__c);
        // error
        delete s;
        try {
            OAuth1 oe1 = new OAuth1(s.Id);
            System.assert(false);
        } catch (OAuthException e) {
        }
        try {
            OAuth1 oe2 = Oauth1.newInstanceByToken('xxx');
            System.assert(false);
        } catch (OAuthException e) {
        }
        Test.stopTest();
    }

    public static testMethod void testHmacSha1OAuth_0() {
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService('HMAC-SHA1');

        Test.startTest();
        // success
        OAuth1 o1 = new OAuth1(s1.Id);
        System.assert(!o1.isCompleteUrl());
        o1.authorization();
        Test.stopTest();
    }

    public static testMethod void testHmacSha1OAuth_1() {
        PageReference completePage = new PageReference('/oauth1/done?oauth_token=token');
        completePage.getHeaders().put('Host', 'localhost');
        Test.setCurrentPage(completePage);
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService('HMAC-SHA1');
        OAuth_Token__c token = new OAuth_Token__c(
            Owner__c = UserInfo.getUserId(),
            OAuth_Service__c = s1.Id,
            OAuth_Token__c = 'oauth_token',
            OAuth_Token_Secret__c = 'oauth_token_secret',
            isAccess__c = false
        );
        insert token;
        OAuth1 o2 = new OAuth1(s1.Id);

        Test.startTest();
        System.assert(o2.isCompleteUrl());
        o2.complete(new Map<String, String> {
            'oauth_token' => 'oauth_token',
            'oauth_verifier' => 'oauth_verifier'
        });
        Test.stopTest();
    }

    public static testMethod void testHmacSha1OAuth_2() {
        Test.setMock(HttpCalloutMock.class, new OAuthCalloutMock());
        OAuthService__c s1 = createTestService('HMAC-SHA1');
        OAuth_Token__c token = new OAuth_Token__c(
            Owner__c = UserInfo.getUserId(),
            OAuth_Service__c = s1.Id,
            OAuth_Token__c = 'oauth_token',
            OAuth_Token_Secret__c = 'oauth_token_secret',
            isAccess__c = true
        );
        insert token;
        OAuth_Token__c token2 = new OAuth_Token__c(
            Owner__c = UserInfo.getUserId(),
            OAuth_Service__c = s1.Id,
            OAuth_Token__c = 'oauth_token',
            OAuth_Token_Secret__c = 'oauth_token_secret',
            isAccess__c = true
        );
        insert token2;
        OAuth1 o3 = new OAuth1(s1.Id);

        Test.startTest();
        System.assert(o3.hasToken());
        HttpRequest req = new HttpRequest();
        req.setEndPoint('https://example/test?page=1&max=100&a=100');
        req.setMethod('POST');
        req.setBody('a=b&c=d');
        OAuthJSON json = o3.json(req);
        json.inspect();
        Test.stopTest();
    }

    public static testMethod void testException() {
        HttpResponse res = new HttpResponse();
        res.setHeader('WWW-Authenticate', 'OAuth error="error", error-desc="desc", error-uri="http://error/", scope="full"');
        OAuth1Exception e1 = new OAuth1Exception(res);
        OAuth1Exception e2 = new OAuth1Exception('test', 'test');
    }
}