src/objects/OAuth2_Token__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expires_In__c</fullName>
        <label>Expires In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OAuth_Service__c</fullName>
        <label>OAuth Service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>OAuth2 Tokens</relationshipLabel>
        <relationshipName>OAuth2_Tokens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OAuth2_Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token_Type__c</fullName>
        <label>Token Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth2 Token</label>
    <nameField>
        <displayFormat>OT2-{00000000}</displayFormat>
        <label>OAuth2 Token No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OAuth2 Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token_URL__c</fullName>
        <label>Access Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Authorization_Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Request Header (Authorization: Bearer)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request Header (Authorization: OAuth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URI Query Parameter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OAuthServiceAPI__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Service__c</fullName>
        <label>OAuth Service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>OAuth Service APIs</relationshipLabel>
        <relationshipName>OAuth_Service_APIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <externalId>true</externalId>
        <label>Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth Service API</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Service APIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OAuthServiceAPIParameter__c.object
<CustomObject>
    <fields>
        <fullName>OAuth_Service_API__c</fullName>
        <label>OAuth Service API</label>
        <referenceTo>OAuthServiceAPI__c</referenceTo>
        <relationshipLabel>OAuth Service API Parameters</relationshipLabel>
        <relationshipName>OAuth_Service_API_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Query String</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request Header</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAuth Service API Parameter</label>
    <nameField>
        <label>Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Service API Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OAuthApiTestControllerTest.cls
@isTest
private class OAuthApiTestControllerTest {
    public static OAuthService__c createTestService() {
        Schema.DescribeSObjectResult d = Schema.SObjectType.OAuthService__c;
        Map<String, Schema.RecordTypeInfo> rti = d.getRecordTypeInfosByName();
        OAuthService__c s = new OAuthService__c(
            Name = 'Twitter',
            Consumer_Key__c = 'consumerkey',
            Consumer_Secret__c = 'consumersecret',
            Access_Token_URL__c = 'https://test/oauth/token',
            Authorization_URL__c = 'https://test/oauth/auth',
            Redirect_URL__c = 'https://localhost/oauth/done',
            OwnerId = UserInfo.getUserId(),
            RecordTypeId = rti.get('OAuth 2.0').getRecordTypeId(),
            Scope__c = 'full',
            Authorization_Type__c = 'Request Header (Authorization: Bearer)'
        );
        insert s;
        return s;
    }

    public static OAuthServiceAPI__c createServiceAPI(OAuthService__c  s) {
        OAuthServiceAPI__c a = new OAuthServiceAPI__c(
            OAuth_Service__c = s.Id,
            Url__c = 'http://test/{Id}',
            Method__c = 'POST',
            Body__c = 'test=0',
            Content_Type__c = 'application/x-www-url-form-encoded'
        );
        insert a;
        List<OAuthServiceAPIParameter__c> ps = new List<OAuthServiceAPIParameter__c> {
            new OAuthServiceAPIParameter__c(OAuth_Service_API__c = a.Id, Type__c = 'Query String', Value__c = 'a'),
            new OAuthServiceAPIParameter__c(OAuth_Service_API__c = a.Id, Type__c = 'Request Header', Value__c = 'b')
        };
        insert ps;
        return a;
    }

    public static OAuth2_Token__c createTestToken(OAuthService__c  s) {
        OAuth2_Token__c t = new OAuth2_Token__c(
            OAuth_Service__c = s.Id,
            Access_Token__c = 'token',
            Refresh_Token__c = 'refresh',
            Scope__c = s.Scope__c,
            Token_Type__c = 'type',
            Expires_In__c = 3600,
            Owner__c = s.OwnerId
        );
        insert t;
        return t;
    }

    public static testMethod void testAll() {
        System.currentPageReference().getParameters().put('@test', 'test');
        OAuthService__c s = createTestService();
        OAuthServiceAPI__c api = createServiceAPI(s);
        createTestToken(s);

        OAuthApiTestController t = new OAuthApiTestController();
        List<SelectOption> ms = t.methodOptions;
        List<SelectOption> ss = t.serviceOptions;
        t.service = s.Id;
        List<SelectOption> sas = t.serviceAPIOptions;
        t.serviceAPI = api.Id;
        t.loadServiceAPI();
        t.template[0].value = 'test';
        t.applyRequest();
        t.add_query();
        t.add_header();
        t.action_index = '0';
        t.delete_query();
        t.action_index = '0';
        t.delete_header();
        t.clearDebug();
        t.execute();
    }
}